name: Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0, 7.0, 8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build TestProject.csproj 

  version2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0, 7.0, 8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Run Version2
        run: dotnet version2 TestProject.csproj  

  version3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0, 7.0, 8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Run Version3
        run: dotnet version3 TestProject.csproj  
